### ISSUE TITLE
release code

### ISSUE THREAD

**Issue by geyanqi** [dingjiansw101/HGFormer#1]

**Comment by Siddharth-Shrivastava7** [comment]
Hi @dingjiansw101 , 

Keep up the great work!  

Could you please let me know, when you will open source the code?

**Comment by dingjiansw101** [comment]
> Hi @dingjiansw101 ,
> 
> Keep up the great work!
> 
> Could you please let me know, when you will open source the code?

Hi Siddharth, I will release it soon after the CVPR. I was occupied with many other things recently.
Best

**Comment by FanoShannon** [comment]
Hi, I have read the paper on CPVR 2023, great work! I wonder will the code be released before September？

**Comment by dingjiansw101** [comment]
@FanoShannon Thanks for paying attention to our work. The code is expected to be released in September.

**Comment by rcNg0229** [comment]
Hi, looking forward to the released code.

**Comment by helen1c** [comment]
Hi @dingjiansw101, looking forward to the released code ...

**Comment by dingjiansw101** [comment]
Hey guys, the code has been released. If you have any problems in using it, please let me know.
