### ISSUE TITLE
The split_data folder is missing. 

### ISSUE THREAD

**Issue by liblacklucy** [dingjiansw101/HGFormer#3]
Hello, thank you for sharing. The split_data folder is miising. Can you provide the cropping processing code for the GTAV dataset?

**Comment by dingjiansw101** [comment]
Thanks for checking. I have updated the split_data folder. Here are the processing codes for gta https://github.com/dingjiansw101/HGFormer/blob/main/datasets/prepare_gta_sem_seg.py
https://github.com/dingjiansw101/HGFormer/tree/main/datasets/split_data/gta
